# Generated by Django 3.1.7 on 2021-04-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(default='teste tags', max_length=150),
            preserve_default=False,
        ),
    ]
